#!/bin/bash
# Script to package generated Java proto files into a Maven-compatible JAR

# Configuration
GROUP_ID="opensearch.proto"
ARTIFACT_ID="opensearch-proto"
VERSION="1.0.0"
JAR_NAME="${ARTIFACT_ID}-${VERSION}.jar"
POM_NAME="${ARTIFACT_ID}-${VERSION}.pom"
OUTPUT_DIR="generated/maven"
MAVEN_LOCAL_REPO="${HOME}/.m2/repository"

# Set up directories
mkdir -p "${OUTPUT_DIR}/classes"
mkdir -p "${OUTPUT_DIR}/META-INF/maven/${GROUP_ID}/${ARTIFACT_ID}"

# Step 1: Generate Java files from proto files (if not already done)
if [ ! -d "generated/java" ] || [ -z "$(find generated/java -name '*.java')" ]; then
  echo "Generating Java files from proto files..."
  ./tools/java/generate_java.sh
fi

# Step 2: Download protobuf-java dependency if needed
PROTOBUF_VERSION="3.14.0"
PROTOBUF_JAR="${OUTPUT_DIR}/protobuf-java-${PROTOBUF_VERSION}.jar"

if [ ! -f "${PROTOBUF_JAR}" ]; then
  echo "Downloading protobuf-java dependency..."
  curl -s -o "${PROTOBUF_JAR}" "https://repo1.maven.org/maven2/com/google/protobuf/protobuf-java/${PROTOBUF_VERSION}/protobuf-java-${PROTOBUF_VERSION}.jar"
fi

# Step 3: Compile Java files
echo "Compiling Java files..."
find generated/java -name "*.java" > "${OUTPUT_DIR}/sources.txt"
javac -cp "${PROTOBUF_JAR}" -d "${OUTPUT_DIR}/classes" @"${OUTPUT_DIR}/sources.txt"

# Step 3: Create POM file
echo "Creating POM file..."
cat > "${OUTPUT_DIR}/META-INF/maven/${GROUP_ID}/${ARTIFACT_ID}/pom.xml" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>${GROUP_ID}</groupId>
  <artifactId>${ARTIFACT_ID}</artifactId>
  <version>${VERSION}</version>
  <name>OpenSearch Protocol Buffers</name>
  <description>Protocol Buffer definitions for OpenSearch</description>

  <dependencies>
    <dependency>
      <groupId>com.google.protobuf</groupId>
      <artifactId>protobuf-java</artifactId>
      <version>3.14.0</version>
    </dependency>
  </dependencies>
</project>
EOF

# Create pom.properties file
cat > "${OUTPUT_DIR}/META-INF/maven/${GROUP_ID}/${ARTIFACT_ID}/pom.properties" << EOF
#Generated by package_proto_jar.sh
#$(date)
version=${VERSION}
groupId=${GROUP_ID}
artifactId=${ARTIFACT_ID}
EOF

# Step 4: Create JAR file
echo "Creating JAR file..."
(cd "${OUTPUT_DIR}/classes" && jar cf "../${JAR_NAME}" .)
jar uf "${OUTPUT_DIR}/${JAR_NAME}" -C "${OUTPUT_DIR}" META-INF

# Step 5: Install to local Maven repository
echo "Installing to local Maven repository..."
GROUP_PATH=$(echo ${GROUP_ID} | tr '.' '/')
ARTIFACT_PATH="${MAVEN_LOCAL_REPO}/${GROUP_PATH}/${ARTIFACT_ID}/${VERSION}"
mkdir -p "${ARTIFACT_PATH}"

# Copy JAR file
cp "${OUTPUT_DIR}/${JAR_NAME}" "${ARTIFACT_PATH}/"

# Copy POM file
cp "${OUTPUT_DIR}/META-INF/maven/${GROUP_ID}/${ARTIFACT_ID}/pom.xml" "${ARTIFACT_PATH}/${POM_NAME}"

# Create maven-metadata.xml file if it doesn't exist
METADATA_DIR="${MAVEN_LOCAL_REPO}/${GROUP_PATH}/${ARTIFACT_ID}"
if [ ! -f "${METADATA_DIR}/maven-metadata.xml" ]; then
  cat > "${METADATA_DIR}/maven-metadata.xml" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>${GROUP_ID}</groupId>
  <artifactId>${ARTIFACT_ID}</artifactId>
  <versioning>
    <release>${VERSION}</release>
    <versions>
      <version>${VERSION}</version>
    </versions>
    <lastUpdated>$(date +%Y%m%d%H%M%S)</lastUpdated>
  </versioning>
</metadata>
EOF
else
  # Update the existing maven-metadata.xml file
  TEMP_FILE=$(mktemp)
  cat > "${TEMP_FILE}" << EOF
<?xml version="1.0" encoding="UTF-8"?>
<metadata>
  <groupId>${GROUP_ID}</groupId>
  <artifactId>${ARTIFACT_ID}</artifactId>
  <versioning>
    <release>${VERSION}</release>
    <versions>
      <version>${VERSION}</version>
    </versions>
    <lastUpdated>$(date +%Y%m%d%H%M%S)</lastUpdated>
  </versioning>
</metadata>
EOF
  mv "${TEMP_FILE}" "${METADATA_DIR}/maven-metadata.xml"
fi

echo "Done! JAR file created at ${OUTPUT_DIR}/${JAR_NAME}"
echo "Installed to local Maven repository at ${ARTIFACT_PATH}"
echo ""
echo "To use this JAR in a Gradle project, add the following to your build.gradle:"
echo ""
echo "repositories {"
echo "    mavenLocal()"
echo "}"
echo ""
echo "dependencies {"
echo "    implementation '${GROUP_ID}:${ARTIFACT_ID}:${VERSION}'"
echo "}"
