generatorName: protobuf-schema
outputDir: spec/protos
inputSpec: build/processed-opensearch-openapi.yaml
additionalProperties:
  addJsonNameAnnotation: true
  flattenComplexType: true
  numberedFieldNumberList: true
  startEnumsWithUnspecified: true
  aggregateModelsName: aggregated_models
  packageName: opensearch
inlineSchemaOptions:
  RESOLVE_INLINE_ENUMS: true
  SKIP_SCHEMA_REUSE: false
